version: "3.8"

services:
  django:
    build: ./web
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
      # - chia
      - cron
  pgdb:
    build: ./pgdb
    container_name: chia_pgdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chiadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
  # chia:
  #   build: ./chia
  #   container_name: chia
  #   restart: always
  #   ports:
  #     - "8445:8444"
  #   volumes:
  #     - chia-data:/root/.chia/
  cron:
    build: ./cron
    container_name: cron
    # entrypoint: /bin/bash
    # command: ["cron", "-f"]
volumes:
  chia-data:
  db-data:
